### ISSUE TITLE
Preventing C&D going forward

### ISSUE THREAD

**Issue by jjskuld** [NzV/NecroBot#12]
So.. looks like NoxxDev got a C&D.  Here are some suggestions (in order of difficulty/feasability):

1. Remove the donation links. Anytime you are trying to make money off of someone else's copyrighted work, you are gonna run into trouble.
2. Remove all references to "Pokemon".  I noticed the Lunat1q got a C&D and so he removed all references to "Pokemon" in his fork of FeroxRev.  We should do something similar.
3. Re-commit the source code in a new repository, so the code is no longer associated with the NecroBot in Github.  I think the "forked from NecronomiconCoding/NecroBot" is going to be an issue going forward.
4. Re-brand NecroBot to something else (kind of like what PokeMobBot did).  

If we wanted even more protection, we could move to semi-open source:

1. Move the repository to BitBucket, which offers free private repositories.
2. Access to repository is by invite only.
3. Invite the core contributes (for example - @samuraitruong @msx752 @mo0ojava)

**Comment by mo0ojava** [comment]
Hi there,
@msx752 and the others already rigged an "new" branch. I think you also got invites to that one?
https://github.com/Necrobot-Private
I'm re-adding you case something went awry.
Also: wise reasoning above. Agree fully.

**Comment by CreativiTimothy** [comment]
You guys can put a discord and then donations within discord if needed (just a suggestion from someone who knows nothing about copyright)
